feat: greate update of action logic (#3)
* feat: differnt report generation

* feat: init new (non-req) variable

* feat: init blueprint ci config

* feat: action can generate conf from vars

* beaty: rework configuring group in action.yaml

* chore: update desc of values

* beaty: init progress bar while scaning img

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,9 +5,22 @@ inputs:
   image_name:
     description: Docker image name
     required: true
+  use_config:
+    description: Using CI config file or generate config from variables
+    required: false
+    default: "false"
   ci_config:
     description: Path to Dive CI configuration file (.dive-ci.yml)
-    required: true
+    required: false
+  lowestEfficiency:
+    description: If the efficiency is measured below X%, mark as failed.Expressed as a ratio between 0-1.
+    required: false
+  highestWastedBytes:
+    description: If the amount of wasted space is at least X or larger than X, mark as failed.Expressed in B, KB, MB, and GB.
+    required: false
+  highestUserWastedPercent:
+    description: If the amount of wasted space makes up for X% or more of the image, mark as failed.Expressed as a ratio between 0-1; fails if the threshold is met or crossed.
+    required: false
   allow_large_image:
     description: Set to true if the image size exceeds 1 GB
     required: false
@@ -16,6 +29,10 @@ inputs:
     description: Set false to fail launches that don't pass the test.
     required: false
     default: "true"
+  report:
+    description: Enable report generation to /tmp/DIVE_REPORT.md
+    required: false
+    default: "false"
 runs:
   using: composite
   steps:
@@ -31,8 +48,31 @@ runs:
         curl -OL https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.deb
         sudo apt install -qqq ./dive_${DIVE_VERSION}_linux_amd64.deb
         echo "::endgroup::"
+        echo "::group::Configure ci..."
+        if [[ "${{ inputs.use_config }}" == "true" ]]; then
+          dive_ci_conf="${{ inputs.ci_config }}"
+        elif [[ "${{ inputs.use_config }}" == "false" ]]; then
+          if [[ -n "${{ inputs.lowestEfficiency }}" && -n "${{ inputs.highestUserWastedPercent }}" && -n "${{ inputs.allow_large_image }}" ]]; then
+            sed -i "s|<efficiency_percent>|${{ inputs.lowestEfficiency }}|g" blueprint.yaml
+            sed -i "s|<wasted_bytes>|${{ inputs.allow_large_image }}|g" blueprint.yaml
+            sed -i "s|<wasted_percent>|${{ inputs.highestUserWastedPercent }}|g" blueprint.yaml
+            cp blueprint.yaml /tmp/ci-config.yaml
+            dive_ci_conf="/tmp/ci-config.yaml"
+          else
+            echo "❌ 'use_config' is false, but one or more required inputs are missing:"
+            echo "   - lowestEfficiency: '${{ inputs.lowestEfficiency }}'"
+            echo "   - highestUserWastedPercent: '${{ inputs.highestUserWastedPercent }}'"
+            echo "   - allow_large_image: '${{ inputs.allow_large_image }}'"
+            exit 1
+          fi
+        else
+          echo "❌ Invalid value for 'use_config': '${{ inputs.use_config }}'. Expected 'true' or 'false'."
+          exit 1
+        fi
+        echo "::endgroup::"
         compiled/godive-action "${{ inputs.image_name }}" \
-         "${{ inputs.ci_config }}" \
+         "$dive_ci_conf" \
          "${{ inputs.allow_large_image }}" \
-         "${{ inputs.continue_on_fail }}"
+         "${{ inputs.continue_on_fail }}" \
+         "${{ inputs.report }}"
       shell: bash
